task_app/urls.py
from django.contrib import admin
from django.urls import path , include

from .router import router


from .views import      TaskListView   \
                    ,   TaskDetailView \
                    ,   TaskCreateView \
                    ,   TaskUpdateView \
                    ,   TaskDeleteView

app_name = "task"

urlpatterns = [
    path("", TaskListView.as_view(), name="all"),
    path("create/", TaskCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", TaskDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete")
]

urlpatterns += router.urls

tasks_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("task/", include("task_app.urls"))
] 

task_app/models.py
from django.db import models
from django.db.models import Model


# Create your models here.
class Task(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model
    """

    nombre = models.CharField(max_length=100, default="Debugear")
    rubro = models.CharField(max_length=100, default="Test", blank=False, null=False)
    # contacto = models.EmailField(max_length=100, default="no_contact@mail.com")
    # ubicacion = models.CharField(max_length=100, default="Tienda online")
    fecha_inicio = models.DateField(blank=False, null=False, auto_now=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
       db_table = "coding_task"


    def __str__(self):
        return f"El nombre de la tarea: {self.nombre} rubro: {self.rubro}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]


# -> Next registrar modelo admin.py

task_app/views.py
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView


from .models import Task

# Create your views here.


class TaskBaseView(View):
    template_name = 'task.html'
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('task:all')


class TaskListView(TaskBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Task
    """

class TaskDetailView(TaskBaseView,DetailView):
    template_name = "task_detail.html"

class TaskCreateView(TaskBaseView,CreateView):
    template_name = "task_create.html"
    extra_context = {
        "tipo": "Crear tarea"
    }

class TaskUpdateView(TaskBaseView,UpdateView):
    template_name = "task_create.html"
    extra_context = {
        "tipo": "Actualizar tarea"
    }

class TaskDeleteView(TaskBaseView,DeleteView):
    template_name = "task_delete.html"
    extra_context = {
        "tipo": "Borrar tarea"
    }

tasks_manager/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    extra_context = {"comision": "TP Grupo 10"}
    template_name = "index.html"

task_app/templates/task.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h2>Tareas</h2>
    <h3><a href="{% url 'task:create' %}">Crear una tarea</a></h3>
    <div class="list">
      {% for task in task_list %}
      <fieldset>
        <legend>Nombre: {{task.nombre}}</legend>
        <ul>
          <!-- <li>Direccion de la task : {{task.ubicacion}}</li> -->
          <li>Rubro: {{task.rubro}}</li>
          <li>Fecha de fin : {{task.fecha_habilitacion}}</li>
        </ul>

        <div>
          <a href="{% url 'task:detail' task.id  %}">
            Detalle de {{task.nombre}} ✅</a
          >
        </div>
        <div>
          <a href="{% url 'task:delete' task.id %}"
            >Borrar {{task.nombre }} ❌</a
          >
        </div>
        <div>
          <a href="{% url 'task:update' task.id %}"
            >Editar {{task.nombre }}📋</a
          >
        </div>
      </fieldset>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock %}

task_app/templates/task_create.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <div>
    <form method="post">
      {% csrf_token %} {{form.as_div}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'task:all' %}">Volvamos a las tareas</a>
  </div>
</main>
{% endblock %}

task_app/templates/task_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h2>Estas seguro que deseas borrar esta tarea?</h2>
    <h2>{{task.nombre}}</h2>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'task:all' %}">Cancelar borrado</a>
  </div>
</main>

{% endblock %}

task_app/templates/task_detail.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>{{task.nombre}}</h1>
    {% for label, value in task.get_fields %}
    <div>
      <span>{{label | upper}}</span>
      <span> <i> {{value}} </i> </span>
    </div>

    {% endfor %}

    <a href="{% url 'task:all' %}">Ir al inicio</a>
  </div>
</main>

{% endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
    <title>Coding-Task</title>
  </head>

  <body>
    <div class="loader">
      <div class="balls"></div>
    </div>

    <header class="header" id="header">
      <nav class="navbar">
        <a href="#top" class="brand">
          <div class="logo"><i class="fa fa-rocket"></i></div>
          <h3>{{comision}}</h3>
        </a>
        <div class="burger" id="burger">
          <span class="burger-line"></span>
          <span class="burger-line"></span>
          <span class="burger-line"></span>
        </div>
        <span class="overlay"></span>
        <div class="menu" id="menu">
          <ul class="menu-inner">
            <li class="menu-item">
              <a class="menu-link" href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="menu-item">
              <a class="menu-link" href="{% url 'task:all' %}">Gestor de Tareas</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    {% block content %} {% endblock %}
  </body>
  <script src=" https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js "></script>
  <script src="{% static './js/index.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="particles-js"></div>

<section class="hero" id="top">
    <div class="title">
        <h1 class="intro">
            <span class="magic">
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg></span>

                <span class="magic-text">Coding-Task </span></span> Grupo {{comision}}
        </h1>
    </div>
</section>

<section class="section">
    <div class="desktop-wrapper">
        <div class="carousel reflect">
            <ul class="carousel__list" data-aos="fade-up" data-aos-duration="1000" data-aos-easing="ease">
                <li class="carousel__item" data-pos="-2"></li>
                <li class="carousel__item" data-pos="-1"></li>
                <li class="carousel__item" data-pos="0"></li>
                <li class="carousel__item" data-pos="1"></li>
                <li class="carousel__item" data-pos="2"></li>
            </ul>
        </div>
    </div>
</section>

{% endblock %}